apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: retail-store
  template:
    metadata:
      labels:
        app: retail-store
    spec:
      containers:
        - name: retail-store-app
          image: myusername/retail-store-app:latest
          ports:
            - containerPort: 80
