name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/retail-store-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/retail-store-app:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubectl-version: "latest"

      - name: Configure kubectl
        run: |
          kubectl config set-cluster my-cluster --server=${{ secrets.K8S_API_SERVER }}
          kubectl config set-credentials deployer --token=${{ secrets.K8S_TOKEN }}
          kubectl config set-context my-context --cluster=my-cluster --user=deployer
          kubectl config use-context my-context

      - name: Apply Kubernetes Resources
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml    # Update your services (retail-store-app, RabbitMQ, etc.)
          kubectl apply -f kubernetes/rabbitmq-deployment.yaml  # Apply RabbitMQ service update
          kubectl apply -f kubernetes/mysql-deployment.yaml    # MySQL Deployment
          kubectl apply -f kubernetes/postgres-deployment.yaml # PostgreSQL Deployment
          kubectl apply -f kubernetes/redis-deployment.yaml    # Redis Deployment
